# Site settings
title: Portraits of Change
email: thomas@PortraitsofChange.org
url: https://example.github.io
description: "Jazz is not a genre, or even a collection of genres; It is a philosophy of music, and of life; to always explore, always wonder, and always seek positive change. The mission of Portraits of Change is to reaffirm the notion that jazz is a musical language of innovation."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
