# Site settings
title: Portraits of Change
email: thomas@PortraitsofChange.org
url: portraitsofchange.org
description: "Bringing Jazz to the 21st Century"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Portraits of Change

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:

  - title: facebook
    url: https://www.facebook.com/JazzPortraitsofChange/
  - title: linkedin
    url: https://linkedin.com/in/thomas-graves-trumpet/

# Build settings
markdown: kramdown
permalink: pretty
